[package]
name = "py-oxide"
version = "0.2.4"
edition = "2021"

[workspace]

[lib]
name = "oxide"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.18.0"
oxide = { path = "../oxide" }
pyo3 = "0.18.1"

[package.metadata.maturin]
python-source = "python"
