name: wheels 

on:
  push:

on:
  push:
  pull_request:

jobs:
  manylinux-x64_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Publish wheel
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma
        with:
          rust-toolchain: nightly-2023-02-14
          maturin-version: '0.14.10'
          command: publish
          args: -m py-oxide/Cargo.toml --skip-existing -o wheels -u yngtodd
